---
- hosts: QA
  become: true
  become_user: root
  tasks:
  - name: installing tomcat
    yum: name=tomcat state=present
  - name: starting tomcat
    service: name=tomcat state=started
  - name: installing gti and docker
    yum: name={{item}} state=present
    loop:
    - docker
    - git
  - name: starting docker
    service: name=docker state=started
  - name: building docker file
    command: docker build -t myadd:ansible .
  - name: creating container
    command: docker run -itd -P myadd:ansible
