---
- hosts: QA
  become: true
  become_user: root
  tasks:
  - name: installing tomcat
    yum: name=tomcat state=present
  - name: starting tomcat
    service: name=tomcat state=started
  - name: installing gti and docker
    yum: name={{item}} state=present
    loop:
    - docker
    - git
  - name: starting docker
    service: name=docker state=started
  - name: cloning the repo that contains addressbook.war and docker files
    git: repo=https://github.com/meghanabotcha/AnsibleDockerdemo.git dest=/tmp/mygitrepo1
  - name: Switching to the directory and building docker file
    command: chdir=/tmp/mygitrepo1 docker build -t myadd:ansible .
  - name: creating container
    command: docker run -itd -P myadd:ansible

